### ISSUE TITLE
pyffmpeg FFprobe list index out of range

### ISSUE THREAD

**Issue by oxidworks** [deuteronomy-works/pyffmpeg#135]
Hello
I tried pyffmpeg on Linux Mint 20.1
pip install pyffmpeg

First test:
```
from pyffmpeg import FFprobe
fp = FFprobe("/home/user/video.mp4")
```

Result:
```
  File "APP.py", line 721, in get_video_duration
    fp = FFprobe("/home/user/video.mp4")
  File "/home/user/.local/lib/python3.8/site-packages/pyffmpeg/pseudo_ffprobe.py", line 52, in __init__
    self.probe()
  File "/home/user/.local/lib/python3.8/site-packages/pyffmpeg/pseudo_ffprobe.py", line 236, in probe
    self._extract_all(str(stdout, 'utf-8'))
  File "/home/user/.local/lib/python3.8/site-packages/pyffmpeg/pseudo_ffprobe.py", line 81, in _extract_all
    all_streams = all_streams.split('Input')[1]
IndexError: list index out of range
```

**Comment by amoh-godwin** [comment]
I haven't been able to replicate the problem, please try another file and lets see.

**Comment by SpikePlayz** [comment]
I have the exact same problem.

**Comment by tetukowski** [comment]
Hi,
I have a similar problem, but I'm working on windows 10.
I use PIP on windows.

from pyffmpeg import FFprobe
xxx = FFprobe('Qc06.000_Qd00.000_h0.50_w2.00_NoDroplet_A.avi')

output:
2023-01-02 12:14:42,370 - pyffmpeg.pseudo_ffprobe.FFprobe - INFO - FFprobe initialised
2023-01-02 12:14:42,371 - pyffmpeg.misc.Paths - INFO - bin folder: C:\Users\User\.pyffmpeg\bin
2023-01-02 12:14:42,371 - pyffmpeg.misc.Paths - INFO - Inside load_ffmpeg_bin
2023-01-02 12:14:42,372 - pyffmpeg.pseudo_ffprobe.FFprobe - INFO - ffmpeg bin: C:\Users\User\.pyffmpeg\bin\ffmpeg.exe
2023-01-02 12:14:42,373 - pyffmpeg.pseudo_ffprobe.FFprobe - INFO - Inside probe
2023-01-02 12:14:42,373 - pyffmpeg.pseudo_ffprobe.FFprobe - INFO - Probing file: "Qc06.000_Qd00.000_h0.50_w2.00_NoDroplet_A.avi"
2023-01-02 12:14:42,374 - pyffmpeg.pseudo_ffprobe.FFprobe - INFO - Issuing commads ['C:\\Users\\User\\.pyffmpeg\\bin\\ffmpeg.exe', '-y', '-i', 'Qc06.000_Qd00.000_h0.50_w2.00_NoDroplet_A.avi', '-f', 'null', 'nul']
2023-01-02 12:14:42,421 - pyffmpeg.pseudo_ffprobe.FFprobe - INFO - Inside _extract_all
Traceback (most recent call last):

  File "C:\Users\User\AppData\Local\Temp\ipykernel_13272\4088098422.py", line 1, in <cell line: 1>
    xxx = FFprobe('Qc06.000_Qd00.000_h0.50_w2.00_NoDroplet_A.avi')

  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyffmpeg\pseudo_ffprobe.py", line 63, in __init__
    self.probe()

  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyffmpeg\pseudo_ffprobe.py", line 271, in probe
    self._extract_all(stdout)

  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pyffmpeg\pseudo_ffprobe.py", line 100, in _extract_all
    all_streams = all_streams.split('Input')[1]

IndexError: list index out of range

Is there anything I can do to solve it? Thank you. 
(I'm sorry i see the problem is closed but i don't understand what should i do with it, if someone could help me)
