### ISSUE TITLE
ffprobe `IndexError: list assignment index out of range` error on some videos.

### ISSUE THREAD

**Issue by TejasIsCool** [deuteronomy-works/pyffmpeg#549]
Error traceback
```
Traceback (most recent call last):
  File "D:\path_to_program\vid_manager.py", line 23, in <module>
    vid_to_img(vidpath)
  File "D:\path_to_program\vid_manager.py", line 7, in vid_to_img
    total_time = FFprobe(vidpath).duration
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyffmpeg\pseudo_ffprobe.py", line 63, in __init__
    self.probe()
  File "C:\Users\name\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyffmpeg\pseudo_ffprobe.py", line 267, in probe
    self._extract_all(stdout)
  File "C:\Users\name\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyffmpeg\pseudo_ffprobe.py", line 110, in _extract_all
    self.metadata[0][x-1] = self._parse_meta(streams[x])
    ~~~~~~~~~~~~~~~~^^^^^
IndexError: list assignment index out of range
```

Just checking via debugging, it seems to me that `self.metadata[0]` is too small to hold more metadata (can only have 2). 

Debugging on line 103 in `pseudo_ffprobe.py` in the `_extract_all` function, I found that the streams variable had gotten 4 elements instead of the expected 3.

List of elements I got: https://pastebin.com/megzdsSz

This issue did not happen on another video.

**Comment by amoh-godwin** [comment]
@TejasIsCool sorry for the delay. I will get on this right away.
