### ISSUE TITLE
 ffprobe IndexError: list index out of range

### ISSUE THREAD

**Issue by sdiop** [deuteronomy-works/pyffmpeg#550]
ffprobe errors out with any file as input.  Peeking into the output of command issued, one can notice the absence of the string 'Input' sought by line 99 & 100 of pseudo_ffprobe.py:
        all_streams = stdout.split('Stream mapping')[0]
        all_streams = all_streams.split('Input')[1]

output of ffmpeg command:

"ffmpeg version N-108453-gb0c7352cd4-tessus Copyright (c) 2000-2022 the FFmpeg developers\n  built with Apple clang version 11.0.0 (clang-1100.0.33.17)\n  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay\n  libavutil      57. 38.100 / 57. 38.100\n  libavcodec     59. 49.100 / 59. 49.100\n  libavformat    59. 33.100 / 59. 33.100\n  libavdevice    59.  8.101 / 59.  8.101\n  libavfilter     8. 49.100 /  8. 49.100\n  libswscale      6.  8.112 /  6.  8.112\n  libswresample   4.  9.100 /  4.  9.100\n  libpostproc    56.  7.100 / 56.  7.100\nHyper fast Audio and Video encoder\nusage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...\n\nUse -h to get full help or, even better, run 'man ffmpeg'\n"

error:

![image](https://user-images.githubusercontent.com/33027241/202910900-26e35bb4-4e98-471d-9a00-013111d6689c.png)

**Comment by amoh-godwin** [comment]
@sdiop sorry for not getting back to you quickly. I will look at this and get back to you

**Comment by amoh-godwin** [comment]
@sdiop please I could not replicate the error. Can you please try passing the filename using (") instead of single quotes(') and lets see what happens. Also I have updated the logs, kindly let me see the logs, like you have done here

**Comment by amoh-godwin** [comment]
@sdiop please the version is: pyffmpeg 2.4.2.13

**Comment by cw-roy** [comment]
I am also having the same issue.  I have tried single-quoting and double-quoting the file name, as well as changing the list position from [0][0] to [0][1] as an experiment.  Any assistance would be appreciated.

pyffmpeg version: 2.4.2.14

My code:

![image](https://user-images.githubusercontent.com/110997104/216126977-421e53dd-c53c-481a-aa36-7f949b40daf4.png)

Output:

(mediaconv) redacted@redacted mediaconv % python3 type_detect.py 
2023-02-01 09:53:17,051 - pyffmpeg.pseudo_ffprobe.FFprobe - INFO - FFprobe initialised
2023-02-01 09:53:17,051 - pyffmpeg.misc.Paths - INFO - bin folder: /Users/redacted/.pyffmpeg/bin
2023-02-01 09:53:17,051 - pyffmpeg.misc.Paths - INFO - Inside load_ffmpeg_bin
2023-02-01 09:53:17,051 - pyffmpeg.pseudo_ffprobe.FFprobe - INFO - ffmpeg bin: /Users/redacted/.pyffmpeg/bin/ffmpeg
2023-02-01 09:53:17,051 - pyffmpeg.pseudo_ffprobe.FFprobe - INFO - Inside probe
2023-02-01 09:53:17,051 - pyffmpeg.pseudo_ffprobe.FFprobe - INFO - Probing file: "/Users/redacted/code/mediaconv/sample_flv.flv"
2023-02-01 09:53:17,051 - pyffmpeg.pseudo_ffprobe.FFprobe - INFO - Issuing commads ['/Users/redacted/.pyffmpeg/bin/ffmpeg', '-y', '-i', '/Users/redacted/code/mediaconv/sample_flv.flv', '-f', 'null', '/dev/null']
2023-02-01 09:53:17,089 - pyffmpeg.pseudo_ffprobe.FFprobe - INFO - Inside _extract_all
Traceback (most recent call last):
  File "/Users/redacted/code/mediaconv/type_detect.py", line 9, in <module>
    fp = FFprobe(input_file)
  File "/Users/redacted/code/mediaconv/mediaconv/lib/python3.9/site-packages/pyffmpeg/pseudo_ffprobe.py", line 63, in __init__
    self.probe()
  File "/Users/redacted/code/mediaconv/mediaconv/lib/python3.9/site-packages/pyffmpeg/pseudo_ffprobe.py", line 271, in probe
    self._extract_all(stdout)
  File "/Users/redacted/code/mediaconv/mediaconv/lib/python3.9/site-packages/pyffmpeg/pseudo_ffprobe.py", line 100, in _extract_all
    all_streams = all_streams.split('Input')[1]
IndexError: list index out of range

**Comment by amoh-godwin** [comment]
@cw-roy sorry for the delay. I will look into this.

**Comment by amoh-godwin** [comment]
@cw-roy @sdiop Please a new version has been made with the fixes: v2.4.2.15
