### ISSUE TITLE
no exception thrown and error property is empty string when converting non-existant file

### ISSUE THREAD

**Issue by stealthrabbi** [deuteronomy-works/pyffmpeg#560]
If the input file does not exist, calling convert() doesn't provide an indication that it failed.

```
from pyffmpeg import FFmpeg

input_file = "/somepath/no_such_file.ogg"
output_file = "/somepath/no_such_file.wav"

ffMpeg = FFmpeg()

output_file = ffMpeg.convert(input_file, output_file)
```

**Comment by amoh-godwin** [comment]
@stealthrabbi thank you for reporting. This will be looked at.

**Comment by stealthrabbi** [comment]
@amoh-godwin sure. I also noticed this issue if the input file exists, but the output file is to a path that doens't exist. The directory doesn't get created automatically, which seems reasonable, but no error is reported when it doesn't get created.

**Comment by amoh-godwin** [comment]
@stealthrabbi Please, I new version has been uploaded with the fixes: v2.4.2.15

**Comment by stealthrabbi** [comment]
I'm getting IndexError: list index out of range when it converts a file. It looks like it's acutallyc reating the file, but the new code seems to be assuming there's something in stderr. And so, I can not convert anything.

```
        if 'Output #0' not in stderr:
>           self.error = stderr.rsplit('\r\n', maxsplit=2)[-2]
E           IndexError: list index out of range
```

**Comment by amoh-godwin** [comment]
@stealthrabbi please which file are you working on, can I have that file?

**Comment by rhyamada** [comment]
I have a issue on same line:

On first sample file from https://samplelib.com/sample-mp4.html

Running  folowing snippet
```python
import pyffmpeg

ff = pyffmpeg.FFmpeg()
ff.convert('sample-5s.mp4', 'sample-5s.mp4.jpeg')
```

On older versions runs OK

```bash
$ pip install 'pyffmpeg<2.4.2.15'
$ python3 a.py 
2023-02-21 07:51:44,067 - pyffmpeg.FFmpeg - INFO - FFmpeg Initialising
2023-02-21 07:51:44,067 - pyffmpeg.FFmpeg - INFO - Save directory: .
2023-02-21 07:51:44,067 - pyffmpeg.misc.Paths - INFO - bin folder: /home/rhyamada/.pyffmpeg/bin
2023-02-21 07:51:44,067 - pyffmpeg.misc.Paths - INFO - Inside load_ffmpeg_bin
2023-02-21 07:51:44,068 - pyffmpeg.FFmpeg - INFO - FFmpeg file: /home/rhyamada/.pyffmpeg/bin/ffmpeg
2023-02-21 07:51:44,068 - pyffmpeg.FFmpeg - INFO - Inside convert function
2023-02-21 07:51:44,068 - pyffmpeg.FFmpeg - INFO - Output file: ./sample-5s.mp4.jpeg
2023-02-21 07:51:44,068 - pyffmpeg.FFmpeg - INFO - Input file: sample-5s.mp4
2023-02-21 07:51:44,068 - pyffmpeg.FFmpeg - INFO - shell: False
2023-02-21 07:51:44,295 - pyffmpeg.FFmpeg - INFO - error message length: 0
```

On .15 version ffmpeg produces the .jpeg file but i got a exception from pyffmpeg
```bash
$ pip install pyffmpeg -U
$ python3 a.py 
2023-02-21 07:57:12,525 - pyffmpeg.FFmpeg - INFO - FFmpeg Initialising
2023-02-21 07:57:12,525 - pyffmpeg.FFmpeg - INFO - Save directory: .
2023-02-21 07:57:12,526 - pyffmpeg.misc.Paths - INFO - bin folder: /home/rhyamada/.pyffmpeg/bin
2023-02-21 07:57:12,526 - pyffmpeg.misc.Paths - INFO - Inside load_ffmpeg_bin
2023-02-21 07:57:12,526 - pyffmpeg.FFmpeg - INFO - FFmpeg file: /home/rhyamada/.pyffmpeg/bin/ffmpeg
2023-02-21 07:57:12,526 - pyffmpeg.FFmpeg - INFO - Inside convert function
2023-02-21 07:57:12,526 - pyffmpeg.FFmpeg - INFO - Output file: ./sample-5s.mp4.jpeg
2023-02-21 07:57:12,526 - pyffmpeg.FFmpeg - INFO - Input file: sample-5s.mp4
2023-02-21 07:57:12,527 - pyffmpeg.FFmpeg - INFO - shell: False
Traceback (most recent call last):
  File "bug.py", line 4, in <module>
    ff.convert('sample-5s.mp4', 'sample-5s.mp4.jpeg')
  File "/home/rhyamada/.local/lib/python3.8/site-packages/pyffmpeg/__init__.py", line 127, in convert
    self.error = stderr.rsplit('\r\n', maxsplit=2)[-2]
IndexError: list index out of range
```

**Comment by amoh-godwin** [comment]
@rhyamada sorry for the delay.  I will be waiting for @need4swede to finish his PR, just to give him a clean PR. But if he delays I will fix this error, before he finishes. Sorry for any inconvenience caused. Thank you.
