### ISSUE TITLE
getting Exception: operable program or batch file on windows 10

### ISSUE THREAD

**Issue by serpentinesr** [deuteronomy-works/pyffmpeg#604]
2023-04-01 01:17:38,359 - pyffmpeg.FFmpeg - INFO - FFmpeg Initialising
2023-04-01 01:17:38,359 - pyffmpeg.FFmpeg - INFO - Save directory: .
2023-04-01 01:17:38,359 - pyffmpeg.misc.Paths - INFO - bin folder: C:\Users\dell pc\.pyffmpeg\bin
2023-04-01 01:17:38,359 - pyffmpeg.misc.Paths - INFO - Inside load_ffmpeg_bin
2023-04-01 01:17:38,359 - pyffmpeg.FFmpeg - INFO - FFmpeg file: C:\Users\dell pc\.pyffmpeg\bin\ffmpeg.exe
2023-04-01 01:17:38,359 - pyffmpeg.FFmpeg - INFO - inside options
2023-04-01 01:17:38,359 - pyffmpeg.FFmpeg - INFO - Options is a String
2023-04-01 01:17:38,359 - pyffmpeg.FFmpeg - INFO - Shell: True
2023-04-01 01:17:38,390 - pyffmpeg.FFmpeg - ERROR - operable program or batch file.
Traceback (most recent call last):
  File "C:\Users\dell pc\Desktop\redditupdate\w.py", line 22, in <module>
    ff.options(f"-i {file} -i watermark.png -filter_complex [1][0]scale2ref=w=oh*mdar:h=ih*0.08[logo][video];[video][logo]overlay=(W-w)/2:H-h-5  {fname}")
  File "C:\Users\dell pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyffmpeg\__init__.py", line 276, in options
    raise Exception(self.error)
Exception: operable program or batch file.

**Comment by amoh-godwin** [comment]
@serpentinesr sorry for the delay. The problem is coming from here: C:\Users\dell pc.pyffmpeg\bin\ffmpeg.exe. The filepath to ffmpeg is wrong. I am scheduling this for tomorrow.

**Comment by serpentinesr** [comment]
@amoh-godwin thanks! Looking at the module, i figured the issue is because my windows user account has a space in it, `dell pc`, is that the issue?
